# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build Tegra develop

on:
  workflow_run:
    workflows: [Build Arm64 CPU develop]
    types:
      - completed

jobs:
  build-and-push:
    # check target platform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # - name: Checkout code
      #   uses: actions/checkout@v3

      - name: Checkout submodule core -- pull submodule
        uses: actions/checkout@v3
        with:
          repository: DecentrAI/core
          path: core

      - name: Checkout submodule core
        run:
          git submodule update --init --recursive

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"


      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: "lab:latest"
          driver: cloud
          endpoint: "naeural/naeural-builder"

      - name: Build and push Tegra
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile_tegra_dev
          push: true
          tags: "naeural/edge_node:tegra_develop"
          platforms: linux/arm64
